application: iloginr
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /stylesheets
  static_dir: static/css
- url: /scripts
  static_dir: static/js
- url: /.*
  script: views/index.py
